backend:
  name: git-gateway
  repo: orca-network/site
  branch: master
  
media_folder: static/assets
public_folder: assets
site_url: https://orca-network-stage.netlify.com

collections:
  - name: "about-orcas" # Used in routes, e.g., /admin/collections/about-orcas
    label: "About Orcas Page" # Used in the UI
    folder: "src/pages/about-orcas" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "templateKey", name: "templateKey", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "habitat" 
    label: "About Orcas Page / Habitat"
    folder: "src/pages/about-orcas/habitat" 
    create: true
    slug: "{{title}}"
    fields: 
      - {label: "templateKey", name: "templateKey", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "natural-history" 
    label: "About Orcas Page / Natural History"
    folder: "src/pages/about-orcas/natural-history" 
    create: true
    slug: "{{title}}"
    fields: 
      - {label: "templateKey", name: "templateKey", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "special-orcas" 
    label: "About Orcas Page / Special Orcas"
    folder: "src/pages/about-orcas/special-orcas" 
    create: true
    slug: "{{title}}"
    fields: 
      - {label: "templateKey", name: "templateKey", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "ways-of-whales" 
    label: "About Orcas Page / Ways of Whales"
    folder: "src/pages/about-orcas/ways-of-whales" 
    create: true
    slug: "{{title}}"
    fields: 
      - {label: "templateKey", name: "templateKey", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  
  - name: "resources" 
    label: "About Orcas Page / Resources"
    folder: "src/pages/about-orcas/resources" 
    create: true
    slug: "{{title}}"
    fields: 
      - {label: "templateKey", name: "templateKey", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}



