backend:
  name: git-gateway
  repo: orca-network/site
  branch: master
  
media_folder: static/assets
public_folder: assets

collections:
  - name: "about-orcas" # Used in routes, e.g., /admin/collections/about-orcas
    label: "About Orcas Page" # Used in the UI
    folder: "src/pages/about-orcas-main" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "templateKey", name: "templateKey", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
  - name: "special-orcas" 
    label: "About Orcas Page / Special Orcas"
    folder: "src/pages/about-orcas-main/special-orcas" 
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "templateKey", name: "templateKey", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

